CS-2240: Added extra library headers
dapi-co/dapi-csharp pull request #12
Opened 2023-03-21 10:18 UTC by kc-sabal

2023-03-21 15:54 UTC, street-jackal submitted a review, later dismissed

2023-03-22 06:27 UTC, asmsh requested changes

2023-03-22 06:27 UTC, asmsh commented on src/Dapi/Products/DapiRequest.cs
> +        public static readonly string LibraryVersion = "1.3.0";
Make them private.

2023-03-22 06:49 UTC, kc-sabal commented on src/Dapi/Products/DapiRequest.cs
> +        public static readonly string LibraryVersion = "1.3.0";
https://github.com/dapi-co/dapi-csharp/pull/12/commits/c14d2496015d4c951aa33d332ffa82eb9bf06f2c

2023-03-22 07:22 UTC, asmsh approved these changes

2023-03-22 07:23 UTC, merged